stage: pretrain

paths:
  ckpt_dir: "./checkpoint"
  log_dir: "./logs"
  mapping_file: "./brats-ssa.json"
  resume_checkpoint_path: null # Path to checkpoint to resume training from

data:
  img_size: [128, 128, 128]
  patch_size: [16, 16, 16]  
  batch_size: 2
  num_workers: 4
  pin_memory: false
  modality_encoder_model: "dmis-lab/biobert-v1.1"

model:
  name: "mae_vit3d_base"
  in_channels: 1
  out_channels: 1 
  spatial_dims: 3
  mask_ratio: 0.6

optimizer:
  type: "adamw"
  lr: 1.0e-4
  weight_decay: 0.05
  betas: [0.9, 0.999]
  eps: 1.0e-8

scheduler:
  type: "warmupcosine" # Options: warmupcosine, cosine, step
  max_epochs: 50
  warmup_epochs: 20
  min_lr: 1.0e-6
  start_factor: 0.001
  end_factor: 1.0
  step_size: 10
  gamma: 0.5

train:
  epochs: 50
  seed: 42
  device: "cuda" # Change to "cuda" if GPU is available
  log_freq: 100
  save_freq: 5
  clip_grad_norm: 1.0
  fold: 0