stage: pretrain

paths:
  data_dir: "./data"
  ckpt_dir: "./checkpoint"
  log_dir: "./logs"
  splits_file: "./splits.json"

data:
  img_size: [128, 128, 128]  
  batch_size: 2
  num_workers: 4
  pin_memory: true

model:
  name: "mae_vit3d_base"
  in_channels: 1
  out_channels: 1 
  spatial_dims: 3
  mask_ratio: 0.6

train:
  num_epochs: 50
  optimizer: {name: "adamw", lr: 1.0e-4, weight_decay: 0.05}
  scheduler: {name: "cosine", warmup_epochs: 20}
  seed: 42
  device: "cpu" # Change to "cuda" if GPU is available
  log_every_steps: 100
  save_every_epochs: 5
  fold: 0